config/routes.rb
Rails.application.routes.draw do
  root to: 'todos#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users, only: [:create, :show, :edit, :update]

  resources :todos

  post '/todos/:id/complete', to: 'todos#toggle_complete'

  resources :categories, only: [:show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :todos
  belongs_to :user

  validates_presence_of :name
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
  belongs_to :category, optional: true

  validates_presence_of :title, :description, :duedate

  def title_digest
    if title.length > 10
      return title[0..9] + '...'
    end
    title
  end

  def self.due_today
    tomorrow = 1.day.since
    today = Time.now

    Todo.where("duedate < ? AND duedate >= ?", "#{tomorrow}", "#{today}").order(:duedate).to_a
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :todos
  has_many :categories

  has_secure_password validations: false
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :logged_in?, :current_user

  def logged_in?
    !!current_user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    if !logged_in?
      flash[:notice] = "You can't do that."
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]
  before_action :require_user
  before_action :require_same_user, only: [:show]

  def new
    @category = Category.new
  end

  def show
    @completed_todos = Todo.where(completed: true, user_id: current_user.id, category: @category).order(:duedate)
    @incomplete_todos = Todo.where(completed: false, user_id: current_user.id, category: @category).order(:duedate)
  end

  def create
    @category = Category.new(category_params)
    @category.user = current_user

    if @category.save
      flash[:notice] = "#{@category.name} was created."
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end

  def require_same_user
    user = @category.user

    if user != current_user
      flash[:notice] = "Can't do that."
      redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:username])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "You've been logged in."
      redirect_to root_path
    else
      flash[:error] = "Something is wrong with your username and/or password."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'You have been logged out'
    redirect_to root_path
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, except: [:new, :index, :create]
  before_action :require_user, except: [:index]
  before_action :require_same_user, only: [:edit, :show, :update, :destroy, :toggle_complete]

  def index
    if logged_in?
      @completed_todos = Todo.where(completed: true, user_id: current_user.id).order(:duedate)
      @incomplete_todos = Todo.where(completed: false, user_id: current_user.id).order(:duedate)
    end
  end

  def show
  end

  def new
    @todo = Todo.new
    @todo.duedate = Time.now
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.user = current_user
    @todo.duedate = Time.new(params[:year], params[:month], params[:day])

    if @todo.save
      flash[:notice] = "#{@todo.title} was created."
      redirect_to todos_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @todo.duedate = Time.new(params[:year], params[:month], params[:day])
    @todo.category = Category.find_by(name: params[:category][:name]) if params[:category]

    if @todo.update(todo_params)
      flash[:notice] = "#{@todo.title} was updated."
      redirect_to todos_path
    else
      render :edit
    end
  end

  def toggle_complete
    if @todo.update(completed: !@todo.completed)
      flash[:notice] = "#{@todo.title} was updated."
      redirect_to todos_path
    else
      render :edit
    end
  end

  def destroy
    if @todo.destroy
      flash[:notice] = "#{@todo.title} has been deleted."
      redirect_to todos_path
    else
      render :show
    end
  end

  private

  def todo_params
    params.require(:todo).permit!
  end

  def set_todo
    @todo = Todo.find(params[:id])
  end

  def require_same_user
    user = @todo.user

    if user != current_user
      flash[:notice] = "Can't do that"
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:new, :create]
  before_action :require_user, except: [:new, :create]
  before_action :require_same_user, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = 'New user was created!'
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = 'Your profile has been updated'
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if params[:id].to_i != current_user.id
      flash[:notice] = "You can't go there."
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_date(dt)
    dt.strftime("%b %e, %Y")
  end
end

app/views/categories/new.html.erb
<h2>Create New Category</h2>

<%= render 'shared/errors', obj: @category %>

<%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit 'Create Category' %>
<% end %>

app/views/categories/show.html.erb
<h2><%= @category.name %></h2>

<strong>Categories:</strong>
<% current_user.categories.each do |category| %>
  <%= link_to category.name, category_path(category) %>
<% end %>

<%= render 'shared/todo_list' %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav.html.erb
<% if logged_in? %>
  <p style="float:right;">Hi <%= current_user.username %></p>
  <%= link_to 'All Todos', root_path %>
  <div>
    <%= link_to 'Log out', logout_path %>
    <%= link_to 'View Profile', user_path(current_user) %>
  </div>
<% else %>
  <div>
    <%= link_to 'Log in', login_path %>
    <%= link_to 'Register', register_path %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticingFlow</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class='row'>
    <div class='alert alert-error span8'>
      <h5>Please fix the following errors:</h5>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<%= link_to 'All todos', root_path %>

<% if logged_in? %>
  <p style="float:right;">Hi <%= current_user.username %></p>
  <div>
    <%= link_to 'Log out', logout_path %>
    <%= link_to 'View Profile', user_path(current_user) %>
  </div>
<% else %>
  <div>
    <%= link_to 'Log in', login_path %>
    <%= link_to 'Register', register_path %>
  </div>
<% end %>

app/views/shared/_todo_item.html.erb
<li>
  <p>
    <%= format_date(todo.duedate) %>
    <br>
    <%= todo.title %>
    <% unless todo.category.nil? %>
      <br>
      Category: <%= link_to todo.category.name, category_path(todo.category) %>
    <% end %>
  </p>
  <br/>
  <%= link_to 'Show', todo_path(todo) %>
  <%= link_to 'Edit', edit_todo_path(todo) %>
  <%= link_to 'Delete', todo_path(todo), method: :delete %>
</li>

app/views/shared/_todo_list.html.erb
<ul>
  <% @incomplete_todos.each do |todo| %>
    <%= render 'shared/todo_item', todo: todo %>
  <% end %>
</ul>
<ul id='complete'>
  <% @completed_todos.each do |todo| %>
    <%= render 'shared/todo_item', todo: todo %>
  <% end %>
</ul>

app/views/todos/_form.html.erb
<%= render 'shared/errors', obj: @todo %>

<div class="span8 well">
  <%= form_for @todo do |f| %>
    <div class="control-group">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="control-group">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>

    <div class="control-group">
      <%= label_tag :month %>
      <%= select_tag :month, options_for_select(1..12, @todo.duedate.month) %>

      <%= label_tag :day %>
      <%= select_tag :day, options_for_select(1..31, @todo.duedate.day) %>

      <%= label_tag :year %>
      <%= select_tag :year, options_for_select(Time.now.year..2050, @todo.duedate.year) %>
    </div>

    <% if current_user.categories.any? %>
      <%= f.label :category %>
      <%= f.select :category_id, current_user.categories.collect { |p| [ p.name, p.id ] }, include_blank: true %>
    <% end %>

    <%= f.submit %>
  <% end %>
</div>

app/views/todos/_todo_item.html.erb
<li>
  <p style="<%= completed_todo_style(todo) %>">
    <%= format_date(todo.duedate) %>
    <br>
    <%= todo.title %>
  </p>
  <br/>
  <%= link_to 'Show', todo_path(todo) %>
  <%= link_to 'Edit', edit_todo_path(todo) %>
  <%= link_to 'Delete', todo_path(todo), method: :delete %>
</li>

app/views/todos/_todo_list.html.erb
<li>
  <p style="<%= completed_todo_style(todo) %>">
    <%= format_date(todo.duedate) %>
    <br>
    <%= todo.title %>
  </p>
  <br/>
  <%= link_to 'Show', todo_path(todo) %>
  <%= link_to 'Edit', edit_todo_path(todo) %>
  <%= link_to 'Delete', todo_path(todo), method: :delete %>
</li>

app/views/todos/edit.html.erb
<h3>Edit Todo</h3>

<%= render 'form' %>

app/views/todos/index.html.erb
<% if logged_in? %>
  <%= link_to 'Create New Todo', new_todo_path %>
  <%= link_to 'Create New Category', new_category_path %>

  <h2>All Todos</h2>

  <% if current_user.categories.any? %>
    <strong>Categories:</strong>
    <% current_user.categories.each do |category| %>
      <%= link_to category.name, category_path(category) %>
    <% end %>
  <% end %>

  <%= render 'shared/todo_list' %>
<% end %>

app/views/todos/new.html.erb
<h3>New Todo</h3>

<%= render 'form' %>

app/views/todos/show.html.erb
<h2><%= @todo.title %></h2>

<p><%= @todo.description %></p>
<p>Due on: <%= format_date(@todo.duedate) %> </p>
<% unless @todo.category.nil? %>
  <p>
    Category: <%= link_to @todo.category.name, category_path(@todo.category) %>
  </p>
<% end %>

<%= link_to 'Edit Todo', edit_todo_path(@todo) %>

<%= link_to (@todo.completed? ? 'Mark Incomplete' : 'Complete Todo'), url_for(controller: 'todos', action: 'toggle_complete'), method: :post %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit submit_msg %>
<% end %>

app/views/users/edit.html.erb
<h2>Edit Profile</h2>

<%= render 'form', submit_msg: 'Update Profile' %>

app/views/users/new.html.erb
<h2>Register New User</h2>

<%= render 'form', submit_msg: 'Register User' %>

app/views/users/show.html.erb
<h5><%= @user.username %></h5>
<%= @user.email %>
<br>
<%= link_to 'Edit Profile', edit_user_path(@user) %>